service: justwatch
app: justwatch
org: igvaquero18

frameworkVersion: '>=3.7.4 <4.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: eu-west-3
  profile: serverless
  memorySize: 128
  timeout: 3
  logRetentionInDays: 7
  environment:
    JUSTWATCH_PROVIDERS: mvs,nfx,prv,dnp,atp,hbm
    JUSTWATCH_CONTENT_TYPES: movie
    JUSTWATCH_VERBOSE: "true"
    JUSTWATCH_TELEGRAM_TOKEN: ${ssm:NOTIFIER_BOT_TOKEN}
    JUSTWATCH_FROM_DAYS: "2"
    JUSTWATCH_CHAT_ID: "-1001483228315"

package:
  patterns:
    - ./bin/**
    - '!./**'

functions:
  searchNew:
    handler: bin/newmovies
    events:
      - schedule: cron(0 10 * * ? *)
